export const RollupContractAbi = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      {
        indexed: true,
        internalType: "bytes32",
        name: "anchorBlock",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "chainLength",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "accountBlob",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "nonceBlob",
        type: "bytes",
      },
      { indexed: false, internalType: "bytes", name: "proof", type: "bytes" },
    ],
    name: "NewState",
    type: "event",
  },
  {
    inputs: [],
    name: "SP1_PROGRAM_VKEY",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "account",
    outputs: [{ internalType: "bytes6", name: "", type: "bytes6" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "anchorBlock",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "chainLength",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes", name: "accountBlob", type: "bytes" },
      { internalType: "bytes", name: "nonceBlob", type: "bytes" },
      { internalType: "bytes", name: "proof", type: "bytes" },
    ],
    name: "commitState",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "io", type: "uint256" }],
    name: "latestStateAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "nonce",
    outputs: [{ internalType: "bytes6", name: "", type: "bytes6" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "programVKey_", type: "bytes32" },
    ],
    name: "setProgramVKey",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "at", type: "uint256" },
      { internalType: "bytes4", name: "selector", type: "bytes4" },
      { internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "state",
    outputs: [{ internalType: "bytes6", name: "", type: "bytes6" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "at", type: "uint256" },
      { internalType: "bytes4", name: "selector", type: "bytes4" },
    ],
    name: "stateAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
